import inteligetneOswietlenieLed from '../../assets/inteligetne-oswietlenie-led.webp';
import systemAutomatykiBudowlanej from '../../assets/system-automatyki-budowlanej.jpg';
import systemZarzadzaniaEnergia from '../../assets/system-zarzadzania-energia.webp';

export const realizations = [
    {
        title: 'Instalacja Elektryczna i Teletechniczna',
        slug: 'instalacja-elektryczna-i-teletechniczna',
        client: 'Uniwersytet Ekonomiczny we Wrocławiu',
        image: systemZarzadzaniaEnergia,
        category: 'Edukacja',
        description: 'Wykonanie instalacji elektrycznej oraz sieci teletechnicznej w pomieszczeniach dziekanatów i korytarza w budynku A.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Utrzymanie Łączności Alarmowej',
        slug: 'utrzymanie-lacznosci-alarmowej',
        client: 'Egis Projects Polska SA',
        image: inteligetneOswietlenieLed,
        category: 'Infrastruktura',
        description: 'Utrzymanie w sprawności łączności alarmowej na autostradzie A4 Wrocław-Katowice.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Farma Fotowoltaiczna i Automatyka Budynkowa',
        slug: 'farma-fotowoltaiczna-i-automatyka-budynkowa',
        client: 'Uniwersytet Opolski',
        image: systemAutomatykiBudowlanej,
        category: 'Edukacja',
        description:
            'Wykonanie farmy fotowoltaicznej, systemu automatyki budynkowej (sterowanie grzejnikami) oraz opomiarowania i odczytów energii elektrycznej.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Wyposażenie Serwerowni',
        slug: 'wyposazenie-serwerowni',
        client: 'SPZOZ w Głuchołazach',
        image: systemZarzadzaniaEnergia,
        category: 'Zdrowie',
        description: 'Wyposażenie serwerowni, system SSWIN, CCTV oraz kontroli dostępu.',
        date: '07-09.2018',
    },
    {
        title: 'Dostosowanie Budynku do Wymogów Przeciwpożarowych',
        slug: 'dostosowanie-budynku-do-wymogow-przeciwpozarowych',
        client: 'Starostwo Powiatowe w Krapkowicach',
        image: inteligetneOswietlenieLed,
        category: 'Administracja',
        description: 'Dostosowanie budynku starostwa do wymogów przeciwpożarowych.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Wymiana Oświetlenia na LED',
        slug: 'wymiana-oswietlenia-na-led',
        client: 'Szpital Wojewódzki w Opolu sp. z o.o.',
        image: systemAutomatykiBudowlanej,
        category: 'Zdrowie',
        description: 'Dostawa i wymiana oświetlenia na energooszczędne w technologii LED.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Sieć LAN i Systemy Bezpieczeństwa',
        slug: 'siec-lan-i-systemy-bezpieczenstwa',
        client: 'Miasto Opole, MOSiR w Opolu',
        image: systemZarzadzaniaEnergia,
        category: 'Sport',
        description: 'Projekt i wykonanie sieci LAN, systemu CCTV, SSWIN oraz kontroli dostępu dla Hali Widowiskowo-Sportowej w Opolu.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Monitorowanie Serwerowni',
        slug: 'monitorowanie-serwerowni',
        client: 'T-Mobile Polska',
        image: inteligetneOswietlenieLed,
        category: 'Telekomunikacja',
        description: 'Monitorowanie serwerowni dla T-Mobile Polska.',
        date: '2016-2017',
    },
    {
        title: 'Przebudowa Sieci Teleinformatycznej',
        slug: 'przebudowa-sieci-teleinformatycznej',
        client: 'Urząd Miasta Opola',
        image: systemAutomatykiBudowlanej,
        category: 'Administracja',
        description: 'Przebudowa sieci teleinformatycznej i dedykowanej sieci na pierwszym i drugim piętrze budynku przy Placu Wolności 7-8 w Opolu.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Modernizacja Infrastruktury Teleinformatycznej',
        slug: 'modernizacja-infrastruktury-teleinformatycznej',
        client: 'Zakład Karny w Głubczycach',
        image: systemZarzadzaniaEnergia,
        category: 'Administracja',
        description:
            'Prace budowlane i modernizacyjne w branży elektrycznej/teletechnicznej w Zakładzie Karnym w Głubczycach (Postępowanie nr DKW – 220/02/2014).',
        date: '19 stycznia 2021',
    },
    {
        title: 'Instalacja Teletechniczna dla Centrum Wystawienniczo-Konferencyjnego',
        slug: 'instalacja-teletechniczna-dla-centrum-wystawienniczo-konferencyjnego',
        client: 'Centrum Wystawienniczo-Konferencyjne w Opolu',
        image: inteligetneOswietlenieLed,
        category: 'Biznes',
        description: 'Wykonanie i instalacja sieci okablowania strukturalnego kat. dla Centrum przy ul. Kępskiej w Opolu.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Kolumny Alarmowe dla AOW A-8',
        slug: 'kolumny-alarmowe-dla-aow-a-8',
        client: 'GDDKiA Wrocław',
        image: systemAutomatykiBudowlanej,
        category: 'Infrastruktura',
        description:
            'Sporządzenie dokumentacji projektowej łączności autostradowej oraz wykonanie kolumn alarmowych dla Autostradowej Obwodnicy Wrocławia AOW A-8.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Modernizacja Punktu Dystrybucyjnego i Okablowania',
        slug: 'modernizacja-punktu-dystrybucyjnego-i-okablowania',
        client: 'Uniwersytet Opolski',
        image: systemZarzadzaniaEnergia,
        category: 'Edukacja',
        description:
            'Modernizacja Centralnego Punktu Dystrybucyjnego sieci przy ul. Oleskiej 48 oraz wykonanie, rozbudowa i modernizacja okablowania strukturalnego w poszczególnych obiektach.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Dostawa i Instalacja Sprzętu Komputerowego',
        slug: 'dostawa-i-instalacja-sprzetu-komputerowego',
        client: '4System Polska',
        image: inteligetneOswietlenieLed,
        category: 'Technologia',
        description:
            'Dostawa, instalacja i uruchomienie sprzętu komputerowego: serwer, komputery z oprogramowaniem, infokioski, sprzęt do wideokonferencji.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Dostosowanie Autostrady A4 do Standardów Płatnych',
        slug: 'dostosowanie-autostrady-a4-do-standardow-platnych',
        client: 'Autostrada A4 Wrocław-Katowice',
        image: systemAutomatykiBudowlanej,
        category: 'Infrastruktura',
        description:
            'Zaprojektowanie i wykonanie dostosowania autostrady A4 (odcinek Wrocław-Sośnica, 153+227 km ÷ 340+200 km) do standardów autostrady płatnej, w tym kabel światłowodowy.',
        date: '19 stycznia 2021',
    },
    {
        title: 'Modernizacja Punktu Dystrybucyjnego przy ul. Oleskiej 48',
        slug: 'modernizacja-punktu-dystrybucyjnego-przy-ul-oleskiej-48',
        client: 'Uniwersytet Opolski',
        image: systemZarzadzaniaEnergia,
        category: 'Edukacja',
        description:
            'Przebudowa przyłącza elektroenergetycznego nN (zasilanie podstawowe) oraz wykonanie modernizacji Centralnego Punktu Dystrybucyjnego przy ul. Oleskiej 48.',
        date: '19 stycznia 2021',
    },
];